version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'kupipodariday'
      POSTGRES_USER: 'student'
      POSTGRES_PASSWORD: '123'
    ports:
      - 5432:5432
